modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/mobiusdt/recipeace/issues"
[[mods]]
   modId="recipeace"
   version="${file.jarVersion}"
   displayName="ReciPeace"
   displayURL="https://github.com/mobiusdt/recipeace"
   #logoFile="recipeace.png" #optional
   authors="MobiusDT"
   description='''
   Recipes and other tweaks for Peaceful mode.
   '''

[[dependencies.recipeace]]
   modId="forge"
   mandatory=true
   versionRange="[35,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.recipeace]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.4,1.17)"
   ordering="NONE"
   side="BOTH"
